/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as CurationRouteImport } from './routes/curation'
import { Route as IndexRouteImport } from './routes/index'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const CurationRoute = CurationRouteImport.update({
  id: '/curation',
  path: '/curation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/curation': typeof CurationRoute
  '/duplicates': typeof DuplicatesRoute
  '/publish': typeof PublishRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/curation': typeof CurationRoute
  '/duplicates': typeof DuplicatesRoute
  '/publish': typeof PublishRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/curation': typeof CurationRoute
  '/duplicates': typeof DuplicatesRoute
  '/publish': typeof PublishRoute
  '/search': typeof SearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/curation' | '/duplicates' | '/publish' | '/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/curation' | '/duplicates' | '/publish' | '/search'
  id: '__root__' | '/' | '/curation' | '/duplicates' | '/publish' | '/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CurationRoute: typeof CurationRoute
  DuplicatesRoute: typeof DuplicatesRoute
  PublishRoute: typeof PublishRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curation': {
      id: '/curation'
      path: '/curation'
      fullPath: '/curation'
      preLoaderRoute: typeof CurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CurationRoute: CurationRoute,
  DuplicatesRoute: DuplicatesRoute,
  PublishRoute: PublishRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
